import os
import torch
from enum import Enum
from os.path import join

# Type of models

class Models(Enum):
    SLOWFAST = "slowfast"
    CNN_3D = "3dcnn"


# ENVIRONMMENT PARAMETERS
CUDA_ACTIVATED = torch.cuda.is_available()

# DATA PROCESSING PARAMMETERS
MAX_SIZE = 368
MEAN = [0.45, 0.45, 0.45]
STD = [0.225, 0.225, 0.225]
CROP_SIZE = 336
NUM_FRAMES = 32
SAMPLING_RATE = 1
FPS = NUM_FRAMES/5
CLIP_DURATION = (NUM_FRAMES * SAMPLING_RATE) / FPS
NUM_WORKERS = 3

# MODEL PARAMETERS
BATCH_SIZE = 5  
CURRENT_MODEL = Models.SLOWFAST

EPOCHS = 30

MOMENTUM_SLOWFAST = 0.9
WEIGHT_DECAY_SLOWFAST = 0.001
LEARNING_RATE_SLOWFAST = 0.01
SIDE_SIZE_SLOWFAST = 336

MOMENTUM_3DCNN = 0.6
WEIGHT_DECAY_3DCNN = 0.01
LEARNING_RATE_3DCNN = 0.01
SIDE_SIZE_3DCNN = 256 

MOMENTUM_MLP = 0.9
WEIGHT_DECAY_MLP = 0.01
LEARNING_RATE_MLP = 0.01


# PATHS
CURRENT_PATH = os.getcwd()
ROOT_PATH = join("/dcs", "pg22", "u2288875", "Documents", "TFM")
CHECKPOINTS_PATH = join(ROOT_PATH, "check_points")
PROCESSED_VIDEO_FOLDER = join(CURRENT_PATH, "processed_data")


PROCESSED_VIDEO_FOLDER_ALL = join(CURRENT_PATH, "data_all")
PROCESSED_VIDEO_FOLDER_FACE_AND_HANDS = join(CURRENT_PATH, "data_face_and_hands")
PROCESSED_VIDEO_FOLDER_BODY_AND_HANDS = join(CURRENT_PATH, "data_body_and_hands")
